# Generated by Django 5.1.3 on 2024-11-24 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_audio', models.FileField(help_text='Archivo de audio identificador del usuario', upload_to='audios_usuarios/')),
                ('nombre', models.CharField(help_text='Nombre del usuario', max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico opcional', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la tarea', max_length=255)),
                ('fecha_planificada', models.DateField(help_text='Fecha planificada para completar la tarea')),
                ('completada', models.BooleanField(default=False, help_text='Indica si la tarea ha sido completada')),
                ('usuario', models.ForeignKey(help_text='Usuario al que pertenece esta tarea', on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='assistant_app.usuario')),
            ],
        ),
    ]
