# Generated by Django 5.1.3 on 2024-11-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_audio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audios_usuarios/'),
        ),
    ]
